learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('topics/add/', views.add_topic, name='add_topic'),
    path('entries/', views.entries, name='entries'),
    path('entries/add', views.add_entry, name='add_entry'),
    path('entries/edit/<int:entry_id>', views.edit_entry, name='edit_entry'),

]

users/urls.py
"""Defines url patterns for users. """
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    # Include default auth urls. 
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey
from django.contrib.auth.models import User
from django.forms.widgets import Widget

class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Entry(models.Model):
    """An entry about learnings related to a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField(help_text="Describe your entry.")
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f'"{self.text[:50]}..." in {self.topic.text}'
        

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text', 'topic']
        labels = {'text': '', 'topic': 'Choose a Topic:'}
        widgets = {'text': forms.Textarea(attrs={'col': 80})}

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['topic'].queryset = Topic.objects.filter(owner=self.user)

learning_logs/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def index(request):
    """The homepage for Learning Log."""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Show topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics, 'count': len(topics)}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show one specific topic and all entries."""
    topic = get_object_or_404(Topic, pk=topic_id, owner=request.user)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def add_topic(request):
    """Add new topic to the database."""
    if request.method != 'POST':
        # No data submitted, show blank form
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.owner = request.user
            topic.save()
            return redirect("learning_logs:topics")
    # Display a blank form or invalid form. 
    context = {'form': form}
    return render(request, 'learning_logs/add_topic.html', context)

@login_required
def entries(request):
    """Show all entries."""
    entries = Entry.objects.filter(topic__owner=request.user).order_by('-date_added')
    context = {'entries': entries, 'count': len(entries)}
    return render(request, 'learning_logs/entries.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an entry."""
    entry = get_object_or_404(Entry, pk=entry_id, topic__owner=request.user)
    if request.method != 'POST':
        form = EntryForm(instance=entry, user=request.user)
    else:
        form = EntryForm(instance=entry, data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
        return redirect('learning_logs:entries')
    context = {'form': form, 'entry': entry}
    return render(request, 'learning_logs/edit_entry.html', context)

@login_required
def add_entry(request):
    topic_id = request.GET.get('topic_id')
    if topic_id:
        topic = Topic.objects.filter(owner=request.user, pk=topic_id)
    else:
        topic = None
    if request.method != 'POST':
        form = EntryForm(initial={'topic': topic}, user=request.user)
    else:
        form = EntryForm(data=request.POST, user=request.user)
        if form.is_valid():
            topic_id = Topic.objects.filter(owner=request.user).get(text=form.cleaned_data.get('topic')).id
            form.save()
            return redirect('learning_logs:topic', topic_id = topic_id)

    context = {'form': form, 'topic': topic}
    return render(request, 'learning_logs/add_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Show blank form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Log the new user and redirect to home page. 
            login(request, new_user)
            return redirect('learning_logs:index')
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/add_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap5 %}

{% block page_header %}
    <h1>New Entry {% if topic %} in <a class="text-decoration-none fst-italic" href="{% url 'learning_logs:topic' topic.id %}">{{ topic.text }}</a>{% endif %}</h1>
{% endblock page_header%}

{% block content %}
    <form method="POST" action="{% url 'learning_logs:add_entry' %}" id="entryForm" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button class="btn btn-primary">Add Entry</button>
        {% endbuttons %}
    </form>
{% endblock content%}

learning_logs/templates/learning_logs/add_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap5 %}
{% block page_header %}
    <h1>Topics:</h1>
{% endblock page_header %}

{% block content %}
<form action="{% url 'learning_logs:add_topic' %}" method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary px-3">Save topic</button>
    {% endbuttons %}
{% endblock content %}

learning_logs/templates/learning_logs/base.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    </style>
</head>
<body>
    <div style="min-height: 100vh;">
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border mx-0">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle Navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a href="{% url 'learning_logs:topics' %}" class="nav-link">Topics</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'learning_logs:entries' %}" class="nav-link">Entries</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}
                            <span class="navbar-text">Hello, {{ user.username }}!</span>
                            <li class="nav-item">
                                <a href="{% url 'users:logout' %}" class="nav-link"><button class="btn btn-sm px-3 btn-secondary">Log out</button></a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a href="{% url 'users:login' %}" class="nav-link fs-5">Login</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'users:register' %}" class="nav-link"><button class="btn btn-primary px-3">Sign Up</button></a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div class="d-flex flex-column justify-content-end align-items-between">
            <main role="main" class="container" style="min-height: 77vh;">
                <div class="pb-2 mb-2 border-bottom">
                    {% block page_header %}
                    {% endblock page_header %}
                </div>
                <div>
                    {% block content %}
                    {% endblock %}
                </div>
            </main>   

            <footer class="d-flex flex-wrap bg-light justify-content-center align-items-center py-3 border-top">
                <p class="text-muted text-center">Copyright &copy; 2021. By <a href="https://www.yagyagaire.tk" class="text-decoration-none"><em>Yagya Gaire</em></a></p>
            </footer>
        </div>
    </div>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap5 %}

{% block page_header %}
    <h3>Editing {{ entry }}</h3>
{% endblock page_header %}

{% block content %}
    <form method="POST" action="{% url 'learning_logs:edit_entry' entry.id %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" role="button" class="btn btn-outline-primary">Save Edit</button>
        {% endbuttons %}
    </form>
{% endblock content%}

learning_logs/templates/learning_logs/entries.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <div class="container d-flex justify-content-between my-3">
        <h1>All Entries</h1>
        <a href="{% url 'learning_logs:add_entry' %}"><button class="btn btn-primary px-3">Add an Entry</button></a>
    </div>
{% endblock %}
{% block content %}

{% include 'learning_logs/entry.html' %}

<p class="text-muted fs-6 fst-italic">Retrived <strong>{{ count }}</strong> records.</p>
{% endblock %}

learning_logs/templates/learning_logs/entry.html
{% block entry %}

{% for entry in entries %}
    <div class="card mb-3">
        <h4 class="card-header fs-5">
            {{ entry.date_added | date:'M d, Y H:i' }}
            <small class="ms-5"><a href="{% url 'learning_logs:edit_entry' entry.id %}"><button class='btn btn-sm px-3 btn-outline-primary'>Edit Entry</button></a></small>
        </h4>
        <div class="card-body">
            {{ entry.text | linebreaks }}
        </div>
    </div>
    
{% empty %}
    <p class="fs-4">No entries found.</p>
{% endfor %}

{% endblock %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Track your learning.</h1>
        <p class="lead">Make your own Learning Log, and keep a list of the topics your're learning about. Whenever you learn something new about a topic, make an entry summarizing what you've learned.</p>
        {% if user.is_authenticated %}
            <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}" role="button">View your Topics &raquo;</a>
        {% else %}
            <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
        {% endif %}
    </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
<div class="container justify-content-between d-flex">
    <h1>Entries in <strong><a class="text-decoration-none" href="{% url 'learning_logs:topic' topic.id %}">{{ topic.text }}</a></strong></h1>
    <a href="{% url 'learning_logs:add_entry'%}?topic_id={{ topic.id | urlencode }}"><button class="btn btn-primary px-3" role="button" name="{{ topic.id }}">Add an Entry</button></a>
</div>

{% endblock page_header %}
{% block content %}
    {% include 'learning_logs/entry.html' %}
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <div class="container d-flex justify-content-between align-items-center my-3">
        <h1 class="d-inline-block">Topics</h1>
        <a href="{% url 'learning_logs:add_topic' %}"><button role="button" class="btn btn-md btn-primary px-3">Add a Topic</button></a>
    </div>
    
{% endblock page_header %}

{% block content %}
    {% if count %}
        <ul class="list-group list-group-flush">
            {% for topic in topics %}
                <li class="list-group-item"><h3><a class="text-decoration-none" href="{% url 'learning_logs:topic' topic.id %}">{{ topic.text }}</a></h3></li>
            {% endfor %}
        </ul>
        <hr>
        <p class="text-muted fs-6 fst-italic">Retrived <strong>{{ count }}</strong> records.</p>
    {% else %}
        <p class="fs-4">No topics have been added yet.</p>>
    {% endif %}
{% endblock %}